### ISSUE TITLE
resolve.aliasFields : string[] (enhanced-resolve) mismatch type declaration

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#12]
`resolve.aliasFields: ['browser']` gives an error. See photo below.

![reboost-3](https://user-images.githubusercontent.com/26875662/89307884-e6336d80-d671-11ea-9b03-54fdec0da1e3.png)

**Comment by sarsamurmu** [comment]
It looks like you are using the old version of Reboost. Upgrade to the latest version to use the new `resolve` options.

**Comment by GHNewbiee** [comment]
Yes, you are right. I did the upgrade to 0.8.0 and no more mismatch.
