### ISSUE TITLE
resolve.cachePredicate : () => boolean (enhanced-resolve) mismatch type declaration

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#13]
*`"reboost": "^0.8.0"`*

`cachePredicate: function() { return true }` gives an error. See photo below.

![reboost-4](https://user-images.githubusercontent.com/26875662/89393832-9ef9bb00-d70b-11ea-82d1-6db928313f0d.png)

**Comment by GHNewbiee** [comment]
Same problem for the following `enhanced-resolve` options:

`cacheWithContext: boolean`
`conditionNames: string[]`
`fileSystem: any`
`fullySpecified: boolean`
`resolver: undefined`
`resolveToContext: boolean`
`unsafeCache: boolean`

**Comment by sarsamurmu** [comment]
Well, I can't say if it's actually an issue. If you see https://github.com/sarsamurmu/reboost/blob/primary/packages/core/src/node/index.ts#L137, I have intentionally disabled them for general users. Do you think we should enable them?

**Comment by GHNewbiee** [comment]
Documentation mentions that:

>`resolve`
>
>Type: `object`
>
>Configurations for module and file resolving. Because it uses `enhanced-resolve`, it supports **all of its options**. `enhanced-resolve` is also used by `webpack`, so you may be already familiar with these options.

I strongly believe that consistency between documentation and implementation is of utmost importance!

**Comment by sarsamurmu** [comment]
I think I have resolved it in another way

**Comment by GHNewbiee** [comment]
I suggest to do the same for the `contentServer` as regards `koa-static` (`koa-send`) and, of course, `http-proxy` and `chokidar`.
