### ISSUE TITLE
public/index.html change never triggers reloading

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#17]
"reboost": "0.9.1"

**reboost.js**
```js
const { start } = require('reboost');

start({
  entries: [
    ['./src/index.js', './public/dist/index.js']
  ],
  contentServer: {
    root: './public',
    open: true
  }
});
```
**src/index.js**
```js
- position: fixed;
+ position: relative;
```
**public/index.html**
```html
...
  <body>
    <p>Welcome Reboost!</p>
    <my-element></my-element>
  </body>
...
```
`public/index.html` page auto-reloading does fail. Do I miss something obvious and important?

**Comment by sarsamurmu** [comment]
If you're making changes to `public/index.html`, it's obvious that the change won't reload the page. The content server still doesn't support file watching, I will try to do something about it.

**Comment by GHNewbiee** [comment]
Then, it would be better to make the following changes temporarily to avoid misleading users/readers:

- **src/index.js**
```html
        <p>
-          Get started by editing
-          <code>src/index.js</code> and <code>public/index.html</code>
+          For the time being, get started by editing
+          only <code>src/index.js</code>.
        </p>
```
- Adjust the content in `watchOptions` to mirror the actual/current situation.
- Add in a prominent place on the home page that "file watching" feature is not yet available.

**Comment by sarsamurmu** [comment]
Now file watching is supported by the content server. Just update to the latest version.
