### ISSUE TITLE
UsePlugin(singleArgument:{}) repetition

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#18]
`UsePlugin({...})` accepts only one argument. Although more than once of it can be used in `plugins` options (I suspect so) (can't they?), don't you think that you don't stay DRY? Plugins are often declared once. I have seen this implementation also in `snowpack` scripts, lately! Wouldn't be better instead of:

```js
plugins: [
    UsePlugin({
      include: /.(png|jpg|jpeg)$/i,
      use: FilePlugin()
    }),
    UsePlugin({
      include: /.*/,
      exclude: /node_modules/,
      use: BabelPlugin()
    }),
...
```
to write something like:
```js
plugins: [
    UsePlugin(
      {
        include: /.(png|jpg|jpeg)$/i,
        use: FilePlugin()
      },
      {
        include: /.*/,
        exclude: /node_modules/,
        use: BabelPlugin()
      }),
...
```
or, in the form of ` UsePlugin([ {}, {}, ... ])`.

**Comment by sarsamurmu** [comment]
Oh right! It would be nice to have this feature. Thanks for the suggestion :D

**Comment by sarsamurmu** [comment]
Added support for this in the latest version.
