### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by nickyhajal** [sarsamurmu/reboost#2]
I'm getting the following error when reboost tries to serve: 

`/node_modules/apollo-upload-client/lib` which I am important as `import { createUploadLink } from "apollo-upload-client"`

![image](https://user-images.githubusercontent.com/1079625/86939900-c0b15380-c107-11ea-90d8-7c9befcab888.png)

**Comment by sarsamurmu** [comment]
Thanks for using Reboost. I will try to look into it as soon as possible :D

**Comment by sarsamurmu** [comment]
Fixed!
