### ISSUE TITLE
"contentServer" mismatch type declaration

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#21]
`contentServer` gives an error, either writing:

```js
contentServer: contentServerConfig,
```
or
```js
  contentServer: {
    ...contentServerConfig,
    open: {
      app: 'firefox'
    }
  },
```
See photo below.

![Screenshot](https://user-images.githubusercontent.com/26875662/89732371-9cba9800-da4e-11ea-9e70-3747e50362f1.png)

**Comment by sarsamurmu** [comment]
That should be fixed

**Comment by sarsamurmu** [comment]
In your content server config file, add `type` JSDoc comment before `module.exports`. Your config file should now look like this
```js
/** @type import('reboost').ReboostConfig['contentServer'] */
module.exports = {
  // Your options
}
```

**Comment by sarsamurmu** [comment]
It's happening because you are using TypeScript type checking with JavaScript files
