### ISSUE TITLE
"esbuildPlugin - jsx.target" mismatch type declaration

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#22]
In `esbuildPlugin`, `jsx.target` property gives an error. See photo below.

![Screenshot](https://user-images.githubusercontent.com/26875662/89733176-f1144680-da53-11ea-92ed-6c659c92002b.png)

**Comment by sarsamurmu** [comment]
You are doing it wrong, it should be like this
```js
{
  loaders,
  jsx: {
    fragment,
    factory
  },
  target,
  minify,
  define
}
```

**Comment by GHNewbiee** [comment]
Yes, sorry!

Just for reference: In case that `esbuildPlugin.config.js` is used then the following has to be added at the beginning of the file:

`/** @type import('reboost').esbuildPlugin['esbuildPluginOptions'] */`

**Comment by GHNewbiee** [comment]
Just for reference: In case that `esbuildPlugin.config.js` is used then the following has to be added at the beginning of the file:

`/** @type import('reboost').esbuildPlugin['esbuildPluginOptions'] */`

**Comment by sarsamurmu** [comment]
Also you can do `/** @type import('reboost').PluginOptions['esbuild'] */`
