### ISSUE TITLE
"contentServer.port" does not fallback to a random port when the given port is unavailable

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#28]
`reboost: 0.10.1`, default `reboost.js` in default location

Although `contentServer.port` is not set, the port used is not random but always `8000`.

**Comment by sarsamurmu** [comment]
Well, actually it uses any available port. If no port is given it starts finding from `8000` then `8001` and increments the number until it's an available port. That's why it's like this.
