### ISSUE TITLE
Changes of files being watched are not displayed.

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#29]
`reboost: 0.10.1`, default `reboost.js` in default location

Files like `reboost.js` and `package. json`, although being watched (`watchOptions.include: /.*/` ***Default*** and `watchOptions.exclude: /node_modules/` ***Default***), their changes are not displayed.

**Comment by sarsamurmu** [comment]
Reboost only watches the files which are requested. It means it does not watch all the files in the directory.

**Comment by GHNewbiee** [comment]
So, I suppose it watches those files which are listed in the terminal when `showResponseTime` is set to `true`, doesn't it?

**Comment by sarsamurmu** [comment]
Yes
