### ISSUE TITLE
[reboost] Unable to resolve path "firebase/app"

### ISSUE THREAD

**Issue by nickyhajal** [sarsamurmu/reboost#3]
I receive the following error when trying to import firebase:

```
import firebase from "firebase/app"
import "firebase/auth
```

![image](https://user-images.githubusercontent.com/1079625/86940333-4af9b780-c108-11ea-971c-d3f558a39260.png)

**Comment by sarsamurmu** [comment]
Thanks for reporting it. I will look into it.

**Comment by sarsamurmu** [comment]
This is now fixed 😀
