### ISSUE TITLE
PostCSSPlugin - How to pass the "path" of PostCSS Config Directory

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#30]
In [`postcss-loader`](https://github.com/webpack-contrib/postcss-loader#object) mentions that:

**Object**

| Name | Type | Default | Description |
|---|---|---|---|
| path | {String} | undefined | PostCSS Config Directory |
| context | {Object} | undefined | PostCSS Config Context |

implying that:

```js
  options: {
    ...
    config: {
      path: '.config/postcss/', ✅
      ctx: { }
    }
  }
```

How can I pass the path through `ctx` in `PostCSSPlugin`?

**Comment by sarsamurmu** [comment]
I didn't notice it. I will add it in the next version.

**Comment by GHNewbiee** [comment]
If I am not wrong `postcss-load-config` is used and not `postcss-loader`. It would nice to add also `options` support at the same time next to `ctx` and `path`.

**Comment by GHNewbiee** [comment]
I have been a little bit confused with the various docs. I suspect the final result will **syntactically** look like the following:

**reboost.js**
```js
plugins: [
    ...,
    PostCSSPlugin({
      path: '/.config_files/postCSS/',
      ctx: {
        usePreset: true,
        cssnano: {}
      }
    }),
    ...
  ]
```
**postcss.config.js**
```js
/** @type import('reboost').PluginOptions['PostCSS'] */

module.exports = ({ file, ctx, env }) => ({
  parser: file.extname === '.sss' ? 'sugarss' : undefined,
  syntax: 'postcss-scss',
  stringifier: 'midas',
  map: 'inline',
  //to: undefined, dont't set it yourself
  //from: undefined, dont't set it yourself
  plugins: {
    'postcss-import': { root: file.dirname },
    'postcss-nested': {},
    // `usePreset` is now available in `options` object
    'postcss-preset-env': ctx.usePreset ? {} : false,
    cssnano: env === 'production' ? ctx.cssnano : false,
  }
})
```
Is that right?

**Comment by sarsamurmu** [comment]
Your configurations are right. But you don't need to add `/** @type */` comment to the postcss config file.

**Comment by sarsamurmu** [comment]
Available in the latest version.
