### ISSUE TITLE
Moving "jsconfig.json" from project root in "Lit-Element" template

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#31]
`jsconfig.json` lying in project root overwrites the corresponding options of `tsconfig.json` in "lit-element" package, doesn't it? Where exactly is the entry/read point of `jsconfig.json` file? I would like to move it to another directory, if possible.

**Comment by sarsamurmu** [comment]
That file is only for VSCode. It's there for enabling support for decorators in VSCode. You can read more here - https://code.visualstudio.com/docs/languages/jsconfig
