### ISSUE TITLE
"lit-element" stopped getting rendered

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#32]
`reboost: 0.12.0`
`lit-element: 2.4.0`
`template: lit-element`
`reboost.js: default`

Regardless of `commonJSInterop.mode` value, rendering of `lit-element`s is over.

**Comment by sarsamurmu** [comment]
Can you try deleting Reboost cache dir?

**Comment by GHNewbiee** [comment]
Unfortunately, it does always fail.

**Comment by GHNewbiee** [comment]
BTW, at the same time, I very often receive errors, like `Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/...'`, too.

**Comment by sarsamurmu** [comment]
I will look into it

**Comment by sarsamurmu** [comment]
It's working fine for me. Check `v0.12.1`, it includes minor fixes which may fix this bug for you.

**Comment by GHNewbiee** [comment]
It does work fine with FF79, but not with 68 any more. Next time, I will also include from the very beginning the brand and version of the browser. For the time being, I am closing this issue but I continue to keep an eye on that...
