### ISSUE TITLE
"plugin-babel - transformContent" mismatch type declaration

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#34]
In **reboost/packages/plugin-babel/src/index.ts**, `transformContent` function gives an error. See photo below.

![Screenshot_1](https://user-images.githubusercontent.com/26875662/91480157-d5f26500-e8a2-11ea-9b4f-f269761b3b73.png)

***Note*** *: In fact, I am trying to write a new plugin for which I follow the pattern of the above-mentioned plugin.*

**Comment by sarsamurmu** [comment]
The returned `map` should be a `RawSourceMap` object, but in your case it's `string`. So you've to do it like this
```js
const result = await swc.transform(...);
const code = result.code;
const map = JSON.parse(result.map);
// Do other things..

return { code, map }
```

**Comment by GHNewbiee** [comment]
Sorry, total hasty negligence of mine.
