### ISSUE TITLE
How to pass a plugin config object to the plugin itself during bootstrap

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#35]
I have had a look at all plugins. Unfortunately, I cannot still figure out a standard way how to pass a plugin config object, e.g.

```js
start({ // `Reboost` config object
  ...
  plugins: [
    samplePlugin({ // `samplePlugin` config object
      pluginSpecificOptions 
    })
  ]
});
```

into `.../plugin-sample/src/index.ts`  `samplePlugin` function when `Reboost` starts.

- `config` argument of `setup` function is the entire `Reboost` config object
- `this.config` is the entire `Reboost` config object, too. In addition, it is not available in `setup` function.

I have seen that, most of the times, an empty object is passed in `options` argument of the function:

`export const CSSPlugin = (options: CSSPluginOptions = {}): ReboostPlugin => {`,
`export = (options: Babel.TransformOptions = {}): ReboostPlugin => {...`,
`export const esbuildPlugin = (options: esbuildPluginOptions = {}): ReboostPlugin => {...`,
`export const PostCSSPlugin = (options: PostCSSPluginOptions = {}): ReboostPlugin => ({`
`export = (options: SveltePluginOptions = {}): ReboostPlugin => {`
or, even simpler
`export = (options: Options = {}): ReboostPlugin => {`

Please, enlighten me. *Tia*

**Comment by GHNewbiee** [comment]
Sorry, empty object is the default value when `options ` is not defined, isn't it? So, `options` does always represent the plugin config object.

**Comment by sarsamurmu** [comment]
Yes, you're correct.
