### ISSUE TITLE
Contradiction and confusion

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#38]
**manually-creating-an-app** mentions:

> and the HTML content (public/index.html)
>
>```js
><!doctype html>
><html>
>  <body>
>    
>    <script type="module" src="./dist/bundle.js"></script>
>  </body>
></html>
>```
>
>then create a file named reboost.js
>
>```js
>const { start } = require('reboost');
>
>start({
>  entries: [
>    // Format - [inputPath, outputPath]
>    ['./src/index.js', './public/dist/bundle.js']
>  ],
>  contentServer: {
>    root: './public',
>    open: true // Opens the browser
>  }
>})
>```

By using `bundle.js`, an initial wrong impression is given that `Reboost` also carries out bundling. One, visiting the site quickly to see what it is about, reads something about bundl\* and leaves; maybe no interested anymore in reading further either the **Note** which declares the opposite or the last question in **FAQs/Troubleshooting**.

**Comment by sarsamurmu** [comment]
Thanks for finding out the flaw.
