### ISSUE TITLE
Does it support route?

### ISSUE THREAD

**Issue by jet10000** [sarsamurmu/reboost#46]
Does it support route?

**Comment by sarsamurmu** [comment]
Can you explain what do you mean by routes? Routing HTML pages or Routing SPAs?

BTW if you mean routing HTML using contentServer you can use [Koa](https://koajs.com/) middlewares, like so
```js
const start = require('reboost');

start({
  contentServer: {
    middleware: async (ctx, next) => {
       if (ctx.path === '/somepath') {
         ctx.body = someResponse;
       }
    }
    // ... Other options
  }
  // ... Other options
});
```
Or you can use [proxies](https://github.com/sarsamurmu/reboost/blob/primary/docs/configurations.md#contentserverproxy) to redirect requests.

**Comment by jet10000** [comment]
Cool,

I’m studying snowpack recently, hoping to integrate server template rendering, such as django’s template and routing, that is, html is rendered by django according to the path, and then svelte, react, and alpine apps are mounted on the page, django `python manage run server`, and then Start `snowpack build --watch --hmr`, and manually insert the HMR client in the django template, but HMR always automatically refreshes the entire page.

I tested the proxy method you mentioned just now, and it works, but the whole page is still refreshed automatically. I still need to study further.

My purpose of doing this is to expect to be able to use svelte, vue, react, alpinejs various component resources. For example, tailwindcss headlessui provides react and vue versions, but does not provide svelte version. Alpinejs version will be provided soon. At the same time, it can use the django backend template and routing that I am familiar with.

So I look forward to finding a solution that can combine these advantages.

The problem I am facing now is how to solve the hmr problem.

Any suggestions and guidelines, thank you

**Comment by sarsamurmu** [comment]
I think it's possible.

First of all assume that the input file is `src/index.js` which is the main file that imports all of your modules. Now your `reboost.js` should look like this
```js
const { start } = require('reboost');

start({
  entries: [
    ['./src/index.js', './public/dist/index.js']
    //                     ^^^ This is our output file path
  ]
});
```
Now in all of your django templates include this markup
```html
<script type="module" src="./public/dist/index.js"></script>
<!--                         ^^^ The path to the output file we put in reboost.js -->
```
Use your own server to serve the files instead of using Reboost's content server.

I think everything should be working now.

**Comment by jet10000** [comment]
App.svelte
```
<script>
  import {onMount} from 'svelte';
  let count = 0;

  onMount(() => {
    const interval = setInterval(() => count++, 1000);
    return () => {
      clearInterval(interval);
    };
  });
</script>

<div class="App">
  <header class="App-header">

    <p>Page has been open for <code>{count}</code> seconds.</p>

  </header>
</div>
```

I just tested it and it works
However, whenever I change the App.svelte file and save it, the client will automatically refresh, but the state information count is lost.

reboost.js

```
const { start, DefaultConfig } = require('reboost');
const SveltePlugin = require('@reboost/plugin-svelte');

start({
  entries: [
    ['./src/index.js', './public/dist/index.js']
  ],
  contentServer: {
    root: './public',
    open: true,
    proxy: {
      '/test': 'http://127.0.0.1:8000',
      }
  },
  resolve: {
    extensions: ['.svelte'].concat(DefaultConfig.resolve.extensions),
    mainFields: ['svelte'].concat(DefaultConfig.resolve.mainFields)
  },
  plugins: [
    SveltePlugin()
  ]
});
```

**Comment by sarsamurmu** [comment]
Hot Reload is not yet supported by the SveltePlugin. I will work on it.

**Comment by sarsamurmu** [comment]
Hot Reloading in Svelte is now supported. Just update Reboost and SveltePlugin to `v0.18.1`.
I think it will work now.

**Comment by jet10000** [comment]
Cheers, it worked

I still have an idea, how to combine alpinejs, snowpack directly uses `npm install alpinejs` and then import it, it will be automatically generated and placed in the web_modules folder, how to do reboost, and may also support hot reload?

My purpose of using alpinejs is to put the template function of django into the component of alpinejs, otherwise I can use vue directly. Because the Django template is rendered first, and then alpine renders the component on the client side. Alpinejs is used for some simple components, and svelte or vue is used for complex components or applications. In addition, alpinejs has some interesting features, and it integrates tailwindcss. How can i do it

I tested the react plugin, but the page is blank.and, there is a spelling error `['./src/index.js','./public/dist/index.js']`, it should be `['. /src/index.jsx','./public/dist/index.js']`

Any suggestions and guidelines, thank you

**Comment by sarsamurmu** [comment]
I am not sure about it. Reboost only works in development, not in production, so it can't generate any bundle or file, atleast for now. Also, I don't think `alpinejs` supports hot reloading. Unfortunately, in this case everything is out of Reboost's control.

**Comment by jet10000** [comment]
I understand, thank you. I imported alpinejs directly into the django template and used it for simple components, such as pop-up menus.

**Comment by sarsamurmu** [comment]
It was a good issue :D
